{
 "title": "Nginx",
 "description": "Real-time NGINX connection and request stats from stub_status for quick insight into server activity.",
 "tags": [ "Wiredoor" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Nginx Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up{}" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "Displays the total number of currently active client connections accepted by NGINX. This includes all connections in Idle (Waiting), Reading, and Writing states. Useful for assessing current connection load.",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_connections_active{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Waiting Connections (Idle)",
   "type": "stat",
   "description": "Represents the number of active connections that are idle, meaning they are kept open by the client but not currently sending or receiving data. A high number may indicate keep-alive usage or connection pooling.",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_connections_waiting{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Writing Connections (Sending)",
   "type": "stat",
   "description": "Indicates the number of active connections where NGINX is currently sending a response to the client. A consistently high value may suggest backend delays or client download latency.\n",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_connections_writing{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reading Connections (Receiving)",
   "type": "stat",
   "description": "Shows the number of active connections where NGINX is currently reading the client's request. Measured at the time of querying the nginx status endpoint. Useful to detect incoming request surges.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_connections_reading{}", "legendFormat": "{{ host }}" }
   ]
  },
  {
   "title": "Connections Accepted Rate (req/sec)",
   "type": "timeseries",
   "description": "Tracks the rate at which client connections are accepted by NGINX per second. Averaged over the selected time range. Helps identify traffic volume trends, spikes, or DoS-like behaviors.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted[1m])",
     "legendFormat": "X Rate (req/sec)"
    }
   ]
  },
  {
   "title": "Connections Handled Rate (req/sec)",
   "type": "timeseries",
   "description": "Measures the rate at which NGINX is successfully handling client connections (i.e., accepted and then fully processed). Should closely follow the accepted rate unless dropped connections occur.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_handled[1m])",
     "legendFormat": "X Rate (req/sec)"
    }
   ]
  },
  {
   "title": "HTTP Request Rate (req/sec)",
   "type": "timeseries",
   "description": "Displays the average number of HTTP requests received per second. Useful for identifying request throughput trends and overall application activity.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total[1m])",
     "legendFormat": "X Rate (req/sec)"
    }
   ]
  }
 ]
}