global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'wiredoor'
    static_configs:
      - targets: ['wiredoor:2020', 'wiredoor:9586']
  - job_name: 'crowdsec'
    static_configs:
      - targets: ['crowdsec:6060']